### ISSUE TITLE
I can't finish this guide

### ISSUE THREAD

**Issue by only-gale** [spring-guides/gs-rest-service#41] opened 2016-04-22 03:05 UTC
I know it's easy, but I encountered a wired problem, a part of console log is blow:
`Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:62)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:54)
        ... 1 more
Caused by: org.springframework.beans.factory.BeanDefinitionStoreException: Failed to read candidate component class: URL [jar:file:/home/gale/workspace/RESTful/target/gs-rest-service-0.1.0.jar!/lib/spring-boot-autoconfigure-1.3.3.RELEASE.jar!/org/springframework/boot/autoconfigure/jdbc/DataSourceAutoConfiguration$JdbcTemplateConfiguration.class]; nested exception is java.lang.IllegalStateException: Could not evaluate condition on org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration$JdbcTemplateConfiguration due to org/springframework/dao/DataAccessException not found. Make sure your own configuration does not rely on that class. This can also happen if you are @ComponentScanning a springframework package (e.g. if you put a @ComponentScan in the default package by mistake)
        at org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.findCandidateComponents(ClassPathScanningCandidateComponentProvider.java:303)
        at org.springframework.context.annotation.ClassPathBeanDefinitionScanner.doScan(ClassPathBeanDefinitionScanner.java:248)
        at org.springframework.context.annotation.ComponentScanAnnotationParser.parse(ComponentScanAnnotationParser.java:137)
        at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:268)
        at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:232)
        at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:199)
        at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:168)
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:321)
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:243)
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:273)
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:98)
        at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:678)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:520)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:766)
        at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:361)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1191)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1180)
        at Application.main(Application.java:8)
        ... 6 more
Caused by: java.lang.IllegalStateException: Could not evaluate condition on org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration$JdbcTemplateConfiguration due to org/springframework/dao/DataAccessException not found. Make sure your own configuration does not rely on that class. This can also happen if you are @ComponentScanning a springframework package (e.g. if you put a @ComponentScan in the default package by mistake)
        at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:55)
        at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:102)
        at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:81)
        at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:64)
        at org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.isConditionMatch(ClassPathScanningCandidateComponentProvider.java:363)
        at org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.isCandidateComponent(ClassPathScanningCandidateComponentProvider.java:347)
        at org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.findCandidateComponents(ClassPathScanningCandidateComponentProvider.java:280)
        ... 25 more
Caused by: java.lang.NoClassDefFoundError: org/springframework/dao/DataAccessException
        at org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration$EmbeddedDataSourceCondition.getMatchOutcome(DataSourceAutoConfiguration.java:217)
        at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:155)
        at org.springframework.boot.autoconfigure.condition.SpringBootCondition.anyMatches(SpringBootCondition.java:138)
        at org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration$DataSourceAvailableCondition.getMatchOutcome(DataSourceAutoConfiguration.java:245)
        at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:47)
        ... 31 more
Caused by: java.lang.ClassNotFoundException: org.springframework.dao.DataAccessException
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at org.springframework.boot.loader.LaunchedURLClassLoader.doLoadClass(LaunchedURLClassLoader.java:178)
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:142)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 36 more`

Why is this? Please help me.

**Comment by gregturn** [comment] 2016-04-22 04:31
Did you start from the initial configuration and copy-and-paste bits from the guide or did you start with the completed section?

**Comment by yg1987613** [comment] 2016-04-22 05:43
@gregturn I followed this guide [http://spring.io/guides/gs/rest-service/](url) step by step, created the folders, copy-and-paste the java code, until successfully I ran "mvn clean package", but the last step was failed when I ran "java -jar target/gs-rest-service-0.1.0.jar". I was using jdk 1.8.0_77.

**Comment by yg1987613** [comment] 2016-04-22 05:52
@gregturn I've tried another guide [http://spring.io/guides/gs/messaging-rabbitmq/](url) in the same environment as the previous one, I got the jar file, but it didn't work successfully either.It almost drives me crazy. I just want to figure one of them out, just one, buddy, then the others would be easier. So please help me.

**Comment by yg1987613** [comment] 2016-04-22 05:57
@gregturn BTW, I love spring so much, and the guides listed on the index page are amazing, even though I haven't succeeded in the first one, but thank you guys anyway.

**Comment by gregturn** [comment] 2016-04-22 12:22
Switched to the "complete" version and run that  see if it works.

**Comment by yg1987613** [comment] 2016-04-23 02:52
@gregturn Yeah, I've already switched to the "complete" version and it ran perfectly, I've been trying to find the difference.

**Comment by gregturn** [comment] 2017-02-10 02:45
@only-gale Would you be willing to push your copy that doesn't work to a separate place in github so I can peek at it?

**Comment by Timeriovo** [comment] 2017-11-14 11:44
sorry，what is "complete"? I have a similar problem with you.
 ide:  eclipse jdk:1.8 maven:3.5.2

**Comment by gregturn** [comment] 2017-11-14 12:48
This guide like many others has two folders, initial and complete. Complete one has all the code for the solution.

**Comment by Pyronia** [comment] 2017-11-21 12:35
Hi!

I had troubles with this guide as well, after few tries the best way to deal with this was to remove:

```
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>1.5.8.RELEASE</version>
    </parent>
```
As the consequence maven will download some additional libraries.

Basically the root cause is difference between used spring versions.
My first attempt was to remove versions from each of the spring dependency after which the project started to work UNTIL I invalidated Cache and restarted my Intellij.

So far everything works for me now.

**Comment by mystyle2006** [comment] 2017-11-23 10:46
Hi guys, as someone who has the same issue, can you please share any information if you got this solved?
email : sayyou0918@gmail.com

**Comment by GWReeves** [comment] 2017-11-23 15:28
Hi Guys, 
I am having a problem running the Spring Rest Service Tutorial... gs-rest-service
(See: "https://spring.io/guides/gs/rest-service/")

There appears to be issues around mapping Java/JSON.

The error I get is... 
"No converter found for return value of type: class hello.Greeting"
The URL I'm using... 
"http://localhost:8080/greeting?name=User"
I'm running the app from within STS as... 
"Spring Boot App"

My environment is:
- Windows 7
- Java 8 (1.8.0_144)
- Maven 3.5.2
- Spring Tool Suite Version: 3.9.1.RELEASE ( Platform: Eclipse Oxygen.1a (4.7.1a) )

It happens with both the self-built "gs-rest-service-initial" and the completed version "gs-rest-service-complete"

These are things I've already checked after reading other peoples suggestions...
1. Yes, the Greeting does have getters
2. The jackson databind, annotaions and core libraries are present (all at version 2.8.10)
3. I tried commenting out the <parent> org.springframework.boot in the pom.xml but it made it worse
4. I also tried restarting STS but it had no effect

I also tied exporting it as a jar to run outside of STS but I got all kinds of issues but that may have been my "jar-ing" 
I did an export as runnable jar with the option "Package required libraries into generated jar"

Anyone have any ideas?

Thanks

**Comment by YuzongG** [comment] 2018-05-21 00:08
If you put your Application.java in the default package, that might be the reason.

**Comment by bicodoc** [comment] 2019-02-27 04:16
The guide leaves a few crucial details unclear to those of us only vaguely familiar with gradle and the OSX terminal.  These comments are based on the directions provided in the "Building a RESTful Web service" guide - https://spring.io/guides/gs/rest-service/

If you get the error "Main class name has not been configured and it could not be resolved", run "gradle bootRun --info" from the "hello" directory and check the "Task:CompileJava" section to ensure you have everything in the correct directories (described below).

1.  The initial gradle build file (build.gradle) should be placed in the eclipse-workspace folder, NOT the source/main/java/hello folder.
2.  The Greeting.java, GreetingController.java and Application.java files should be placed, as indicated, in the source/main/java/hello.  They do not need to be compiled (and compilation will fail for GreetingController.java and Application.java).
3.  run "gradle build" from the eclipse-workspace folder - it will create the gs-rest-service-0.1.0.jar in eclipse-workspace/build/libs.
4.  from the eclipse-workspace folder, run "java -jar build/libs/gs-rest-service-0.1.0.jar".  After some messages, the service is up and running.  You can proceed to http://localhost:8080/greeting to test the results.

**Comment by wild-o** [comment] 2019-07-07 01:56
I'm having problems with this guide too. Over and over again it has been saying that I do not have a main method defined. I removed one of the default plugins that the original POM file came with and now I am getting an error that says that an exception occurred while running.

**Comment by wild-o** [comment] 2019-07-08 04:36
Update: I tried this again using their version with the complete Maven build, and it did not work for me when I tried to use ./mvnw spring-boot:run 

I was able to build the jar file but then when I tried to run the jar file... nada.

I'm just gonna move on to another guide. I don't know what I'm doing wrong.

**Comment by dsyer** [comment] 2020-01-15 11:01
This is now a collection of many different gripes and user errors. No-one so far has provided any steps to reproduce their problem or sample projects. I'm going to close this issue. Please open a new one if you have trouble building the samples in the guide (and be sure to check out the code and run it from the "complete" sample).

**Closed by dsyer** 2020-01-15 11:01 UTC
